const express = require("express");
const router = express.Router();
const {handelUserSignup , handelUserlogin , changeEmail,changePhoneNumber,handelGetUsers,handelAllUsers } = require("../controllers/users");
router.post("/",handelUserSignup);
router.post("/login",handelUserlogin);
router.post("/login/changeEmail",changeEmail);
router.post("/login/changePhoneNumber",changePhoneNumber);
router.get("/login/handelGetUsers", handelGetUsers);
router.post("/login/handelAllUsers" , handelAllUsers);
module.exports = router;
